const HTTP_CODES = {
    'OK': 200,
    'PERMANENT_REDIRECT': 301,
    'TEMPORARY_REDIRECT': 302,
    'BAD_REQUEST': 400,
    'FORBIDDEN': 403,
    'NOT_FOUND': 404,
    'CONFLICT': 409,
    'INTERNAL_SERVER_ERROR': 500,
  };
  
  module.exports = HTTP_CODES;
  